package com.tmm.dao;

import com.tmm.entity.Activity;

import java.util.List;

public interface ActivityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    List<Activity> selectAll();
}