package com.tmm.dao;

import com.tmm.entity.CustomerType;

import java.util.List;

public interface CustomerTypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbggenerated
     */
    int insert(CustomerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbggenerated
     */
    List<CustomerType> selectAll();
}