server:
  port: 8888
  servlet:
    context-path: /tmm
spring:
  profiles:
    active: dev   
  datasource:
    url: jdbc:mysql://localhost:3306/tmm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: false
    
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback.xml
  level:
    com.tmm.dao: debug

  
    