package com.tmm.entity;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.CUSTOMER_ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.SITE_ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    private String siteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.ID
     *
     * @return the value of activity.ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.ID
     *
     * @param id the value for activity.ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.CUSTOMER_ID
     *
     * @return the value of activity.CUSTOMER_ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.CUSTOMER_ID
     *
     * @param customerId the value for activity.CUSTOMER_ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.SITE_ID
     *
     * @return the value of activity.SITE_ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.SITE_ID
     *
     * @param siteId the value for activity.SITE_ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }
}