package com.tmm.entity;

public class CustomerType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_type.ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_type.DESCRIPTION
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_type.ID
     *
     * @return the value of customer_type.ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_type.ID
     *
     * @param id the value for customer_type.ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_type.DESCRIPTION
     *
     * @return the value of customer_type.DESCRIPTION
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_type.DESCRIPTION
     *
     * @param description the value for customer_type.DESCRIPTION
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }
}