package com.tmm.entity;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CUSTOMER_TYPE
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    private String customerType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.ID
     *
     * @return the value of customer.ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.ID
     *
     * @param id the value for customer.ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CUSTOMER_TYPE
     *
     * @return the value of customer.CUSTOMER_TYPE
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CUSTOMER_TYPE
     *
     * @param customerType the value for customer.CUSTOMER_TYPE
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType;
    }
}