package com.tmm.entity;

public class Site {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.SITE_TYPE
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    private String siteType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.ID
     *
     * @return the value of site.ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.ID
     *
     * @param id the value for site.ID
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.SITE_TYPE
     *
     * @return the value of site.SITE_TYPE
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public String getSiteType() {
        return siteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.SITE_TYPE
     *
     * @param siteType the value for site.SITE_TYPE
     *
     * @mbggenerated Mon Jan 04 16:00:51 CST 2021
     */
    public void setSiteType(String siteType) {
        this.siteType = siteType;
    }
}